/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function LmaoText({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/IXx6lCMY3GQeSn2W/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#e7e7e7"]} />
      <group {...props} dispose={null}>
        <mesh
          name="Text"
          geometry={nodes.Text.geometry}
          material={materials["Text Material"]}
          castShadow
          receiveShadow
          position={[-17.74, 48.5, 10.43]}
        />
        <directionalLight
          name="Light Main"
          castShadow
          intensity={1}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[-129.8, 169.47, 157.37]}
        />
        <directionalLight
          name="Key Light"
          castShadow
          intensity={0.2}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[138.73, 169.47, -75.64]}
        />
        <mesh
          name="Floor"
          geometry={nodes.Floor.geometry}
          material={materials["Floor Material"]}
          castShadow
          receiveShadow
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1}
        />
        <OrthographicCamera
          name="1"
          makeDefault={true}
          far={100000}
          near={-100000}
          position={[533.35, 485.18, 692.92]}
          rotation={[-0.61, 0.56, 0.36]}
        />
        <hemisphereLight
          name="Default Ambient Light"
          intensity={0.75}
          color="#eaeaea"
        />
      </group>
    </>
  );
}
